name: cargo test --all

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]

    steps:
    - uses: actions/checkout@v1

    # which host are we running on?
    - name: hostname
      run: hostname

    # Ubuntu system dependencies required to build Postgres from sources
    - name: install llvm
      run: sudo apt-get install clang llvm make curl

    # test our code
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        - uses: actions-rs/cargo@v1
          with:
            command: test
            args: --all